language: ruby
rvm:
  - 1.9.3
env:
  - DB=sqlite
script:
  - rails g devise:install -f
  - bundle exec rake --trace db:migrate
  - bundle exec rake --trace db:test:prepare
after_script:
  - rake cucumber features